language: python
sudo: false
notifications:
    webhooks:
        - secure: "QXcEHVnOi5mZpONkHSu1tydj8EK3G7xJ7Wv/WYhJ5soNUpEJgi6YwR1WcxSjo7qyi8hTL+4jc+ID0TpKDeS1lpXF41kG9xf5kdxw5OL0EnMkrP9okUN0Ip8taEhd8w+6+dGmfZrx2nXOg1kBU7W5cE90XYqEtNDVXXgNeilT+ik="

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "pypy"
    - "pypy3"

env:
    - RUN=nosetests
    - RUN=build_sphinx

matrix:
    allow_failures:
        - python: "3.8-dev"
        - python: "pypy"
        - python: "pypy3"

install:
    - ./.travis.install.sh

script:
    - ./.travis.script.sh
